version: "3"
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sqlpass
      - MYSQL_DATABASE=cust
      - MYSQL_USER=sql
      - MYSQL_PASSWORD=sqlpass
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
